import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "./components/Header/Header";
import { Footer } from "./components/Footer/Footer";
import { Sidebar } from "./components/Sidebar/Sidebar";

const noto_sans = Noto_Sans({
	subsets: ["cyrillic"],
});

export const metadata: Metadata = {
	title: "My top - наш лучший топ",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru" className={noto_sans.className}>
			<body>
				<div className="wrapper">
					<Header className="header" />
					<Sidebar className="sidebar" />
					<div className="main-content">{children}</div>
					<Footer className="footer" />
				</div>
			</body>
		</html>
	);
}
