import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const noto_sans = Noto_Sans({
	subsets: ["cyrillic"],
});

export const metadata: Metadata = {
	title: "My top - наш лучший топ",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru" className={noto_sans.className}>
			<body>{children}</body>
		</html>
	);
}
